# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: 
  engines:
    keep_only:
      - bing
engines:
  - name: bing
    engine: bing
    disabled: false
  
server:
  secret_key: "f81603d4191caab069b021fa0568391a33c8a837b470892c64461b5dd12464f4" # change this!
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json
